services:
  - type: web
    name: vivid
    env: node
    plan: free
    buildCommand: npx npm@latest install
    startCommand: node index.js
    repo: https://github.com/Glztch/vivid-casino-proxy
    branch: main
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
