services:
  - type: web
    name: vivid
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    repo: https://github.com/Glztch/vivid-casino-proxy
    branch: main
    nodeVersion: 22.0.0
